### ISSUE TITLE
 Display box 

### ISSUE THREAD

**Issue by taybee** [GlobalcachingEU/GSAKWrapper#11]
when you run the GsakWrapper you get the number's of caches at each box  it would be good  to add a display  box to show a list of  GC Number's  , cache name  in Gsakwrapper

**Comment by RobertoPeters** [comment]
That could be 100.000 geocaches and a huge memory and performance hit.
If you want to check intermediate results, you might want to connect a Set User Flag block to that block and temporary remove it from other (final) blocks

**Comment by JensFF** [comment]
This could be a pop up box which opens and fills when the cursor stays on the number of caches. So it's a performance hit on demand.
May additional blocked by an option too.

**Comment by RobertoPeters** [comment]
The tempoary table are removed after the run. This means that to get the data, you have to run it again. If this is really a desired feature, we might consider an optional setting. Maybe if you set this option, the intermediat results are not stored in tempoary tables, but in an actual (other) database.
