### ISSUE TITLE
Sequences not working

### ISSUE THREAD

**Issue by JensFF** [GlobalcachingEU/GSAKWrapper#12]
I can add a new sequence but neither edit nor delete it again.
I one of the previous betas I could use it.

**Comment by RobertoPeters** [comment]
Confirmed and I will have a look at it.

**Comment by JensFF** [comment]
Thanks. This is an important feature for me.

**Comment by RobertoPeters** [comment]
should be fixed in V0.8.3.0

**Comment by JensFF** [comment]
Editor is working again. I will check function tomorrow.
