### ISSUE TITLE
Cache images not copied

### ISSUE THREAD

**Issue by JensFF** [GlobalcachingEU/GSAKWrapper#14]
When copying caches to another database, the CacheImages entry in database becomes empty.

The screen shot shows SQLite-manager views of a cache copied by GSAK Wrapper.
![cacheimages](https://cloud.githubusercontent.com/assets/16364238/11994588/8d76af24-aa41-11e5-96c6-2b964073902f.png)

Found this because SendImagesToGarmin.gsk isn't working on my trip database.generated by GSAK Wrapper.

**Comment by JensFF** [comment]
Checking the other fields, I found another difference in the custom fields.
![custom](https://cloud.githubusercontent.com/assets/16364238/11994661/ca14f7be-aa42-11e5-97e2-f912e66b22e3.png)

**Comment by JensFF** [comment]
This is a real problem when moving caches!

**Comment by RobertoPeters** [comment]
Thanks for the report! I will look into this (as with other items next week)

**Comment by RobertoPeters** [comment]
fixed in version 0.9.0.0

**Comment by JensFF** [comment]
Not working for me:
_Error: SQL logic error or missing database
no such column CacheImage.Code_
Should this be CacheImage.**i**Code?

Also custom fields are not copied. But this may be due the previous error.

**Comment by RobertoPeters** [comment]
That is weird. I am afraid I tested it with caches without cacheimages I guess. Will fix it.

**Comment by RobertoPeters** [comment]
This issue should be solved now in version 0.9.1.0
The custom table needs to be looked in to. Columns might need to be created.
