### ISSUE TITLE
Feature: Connection point

### ISSUE THREAD

**Issue by JensFF** [GlobalcachingEU/GSAKWrapper#15]
How about a connection point which has just on input and one output and no operation (NOP). I would use to combine the inputs or out put of an "OR" and handle them at a single connection.

Example:
I want to filter for (traditional or mystery) and then for (state=a or state=b). Without the connection point if have to connect each put of the first filter to each input of the second. This looks weird (esp. if more conditions are used).
It's also easier to insert additional conditions after such a combination.

I hope,I've made my point clear. Otherwise I could create some screen shots.

**Comment by RobertoPeters** [comment]
Maybe I understand it, but just to be sure; a screenshot would be helpful to clearify your request.

**Comment by JensFF** [comment]
Current implementation, each output connected to each input:
![without nop](https://cloud.githubusercontent.com/assets/16364238/12002417/c4f80efe-aafd-11e5-9e34-00cf04b0aa72.png)
with NOP:
![nop](https://cloud.githubusercontent.com/assets/16364238/12002424/e161faf0-aafd-11e5-82bf-9825b57db56c.png)
The NOP may even be a small circle only.

**Comment by RobertoPeters** [comment]
Glad to see I did understand you correctly. I will add an 'OR' block ('Join' block or 'NOP' block, I still need to see what the correct name for such a block would be)

**Comment by RobertoPeters** [comment]
Added 'Pass through' filter in 'Extra' tab
