### ISSUE TITLE
Distance from location shall access places list from GSAK

### ISSUE THREAD

**Issue by JensFF** [GlobalcachingEU/GSAKWrapper#19]
It would be nice to access the places defined in GSAK

**Comment by RobertoPeters** [comment]
This is already present.
However, the locations are read from the GSAK database once at startup of GSAKWrapper. They are then presnt in the drop down list of the filter 'Distance from location'

**Comment by JensFF** [comment]
I always get empty drop down list.
Wanted to add screen shot but I'm not able to upload.
