### ISSUE TITLE
Output of "Attributes" filter are identical

### ISSUE THREAD

**Issue by JensFF** [GlobalcachingEU/GSAKWrapper#20]
= and <> output give the same caches

**Comment by RobertoPeters** [comment]
I will have a look at it. Can you add an export to this issue which I can import to test?

**Comment by RobertoPeters** [comment]
Found the problem. The "Attributes" filter ignores the operator.
I will fix this

**Comment by RobertoPeters** [comment]
fixed in V1.0.2.0

**Comment by JensFF** [comment]
Thanks for the fix. Looks god now.
